CREATE TABLE IF NOT EXISTS categorys (
 	id TINYINT NOT NULL PRIMARY KEY,
 	category VARCHAR(10) NOT NULL
 );
 
CREATE TABLE IF NOT EXISTS restaurants (
	restaurant_id MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	category_id TINYINT NOT NULL,
	name VARCHAR(50) NOT NULL,
	image_name VARCHAR(255) NOT NULL,
	address VARCHAR(200) NOT NULL,
	phone_number VARCHAR(15) NOT NULL,
	description VARCHAR(500) NOT NULL,
	budget VARCHAR(20) NOT NULL,
	opening_hours VARCHAR(100) NOT NULL,
	capacity TINYINT NOT NULL,
	holiday VARCHAR(50) NOT NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (category_id) REFERENCES categorys (id)
);

CREATE TABLE IF NOT EXISTS roles (
	id TINYINT NOT NULL PRIMARY KEY,
	name VARCHAR(11) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
	id MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	furigana VARCHAR(50) NOT NULL,
	phone_number VARCHAR(15) NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	birthday INT NOT NULL,
	password VARCHAR(25) NOT NULL,
	occupation TINYINT NOT NULL,
	role_id TINYINT NOT NULL, 
	delete_flag TINYINT NOT NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (role_id) REFERENCES roles (id)
 );
